<!-- BREAD CRUMB NAVIGATOR PANEL -->
<div class="bread_crumb_module">
    <div class="bread_crumb">
        <ul>
            <li><a href="/dashboard">Home</a></li>
            <li><?php echo $this->title; ?></li>
        </ul>
    </div><!-- end bread_crumb div -->
</div><!-- end bread_crumb_module div -->
<div class="clear"></div>

<!-- SYSTEM MESSAGES -->
<?php if (is_array($this->messages) && count($this->messages) > 0) { ?>
    <div id="messages">
        <ul>
            <?php foreach ($this->messages as $message) { ?>
                <li><?php echo $message; ?></li>
            <?php } ?>
        </ul>
    </div><!-- end messages div -->
<?php } ?>

<div class="table_top_options">    
    <div class="options_section">[ <a href="/shipping/asnshipment">Create New ASN</a> ]</div>
</div>
<div class="clear"></div>

<table class="shipping_sort_table" style="border:1px solid #666;margin:auto;text-align:left;width:1000px;">
    <thead>        
        <tr>
            <th colspan="11" class="top-header">ASN Shipments</th>
        </tr>
        <tr>
            <th>#</th>
            <th>Cus No</th>
            <th>PO No</th>
            <th>Order No</th>
            <th>PO Lines</th>
            <th>Order Date</th>
            <th>Uploaded</th>
            <th>CSA</th>
            <th>PO</th>
            <th>Status</th>
            <th></th>
        </tr>
    </thead>  
    <tbody>
        <?php $i = 0;
        foreach ($this->asnheader as $asn) {
            ++$i; ?>
            <tr class="row_<?php echo $i % 2; ?>">
                <td><?php echo $i; ?></td>
                <td><?php echo $asn['cust_no']; ?></td>
                <td><?php echo $asn['po_no']; ?></td>
                <td><?php echo $asn['conf_orderno']; ?></td>
                <td><?php echo $asn['lines']; ?></td>
                <td><?php echo date('m/d/Y', strtotime($asn['order_date'])); ?></td>
                <td><?php echo date('m/d/Y H:i:s', strtotime($asn['processed_datetime'])); ?></td>
                <td><?php echo $asn['name']; ?></td>
                <td><a target="_blank" href="/uploads/spsorders/<?php echo $asn['order_file']; ?>">View PO</a></td>
                <td><?php
                    if ($asn['complete'] == 1) {
                        echo'Complete';
                    } else if ($asn['labels_count'] > 0) {
                        echo'Printed';
                    } else {
                        echo 'New';
                    }
                    ?>
                </td>
                <td>
                    <?php if (!empty($asn['conf_orderno'])) { ?>
                        <a href="/shipping/asnshipment/orderno/<?php echo $asn['conf_orderno']; ?>">
                            <img src="/images/icons/famfam/pencil.png" title="Edit shipment" />
                        </a>
            <?php } ?>
                </td>
            </tr>
<?php } ?>
    </tbody>
</table>
