<!-- BREAD CRUMB NAVIGATOR PANEL -->
<div class="bread_crumb_module">
    <div class="bread_crumb">	
        <ul>
            <li><a href="/dashboard">Home</a></li>
            <li><?php echo $this->title; ?></li>
        </ul>
    </div><!-- end bread_crumb div -->
</div><!-- end bread_crumb_module div -->
<div class="clear"></div>

<!-- SYSTEM MESSAGES -->
<?php if (is_array($this->messages) && count($this->messages) > 0) { ?>
    <div id="messages">
        <ul>
            <?php foreach ($this->messages as $message) { ?>
                <li><?php echo $message; ?></li>
            <?php } ?>
        </ul>
    </div><!-- end messages div -->
<?php } ?>

<div class="form_options">[ <a href="/variables/allergens">Cancel</a> ]</div>

<form method="post" action="">
    <?php echo $this->form->allergens_id; ?>
    <table id="form">
        <tr>
            <td colspan=2 class="top-header">Allergens Manager</td>
        </tr>
        <tr>
            <td class="form-header">Item Key</td>
            <td class="form-field"><?php echo $this->form->allergens_item; ?></td>
        </tr>
        <tr>
            <td class="form-header">Allergens</td>
            <td class="form-field"><?php echo $this->form->allergens_data; ?></td>
        </tr>
        <tr>
            <td class="form-header">Organic</td>
            <td class="form-field"><?php echo $this->form->allergens_organic; ?></td>
        </tr>
        <tr>
            <td class="form-header">Cooler</td>
            <td class="form-field"><?php echo $this->form->allergens_cooler; ?></td>
        </tr>
        <tr>
            <td colspan=2 class="form-submit"><?php echo $this->form->submit; ?></td>
        </tr>
    </table>
</form>