<!-- BREAD CRUMB NAVIGATOR PANEL -->
<div class="bread_crumb_module">
    <div class="bread_crumb">	
        <ul>
            <li><a href="/dashboard">Home</a></li>
            <li><?php echo $this->title; ?></li>
        </ul>
    </div><!-- end bread_crumb div -->
</div><!-- end bread_crumb_module div -->
<div class="clear"></div>

<!-- SYSTEM MESSAGES -->
<?php if (is_array($this->messages) && count($this->messages) > 0) { ?>
    <div id="messages">
        <ul>
            <?php foreach ($this->messages as $message) { ?>
                <li><?php echo $message; ?></li>
            <?php } ?>
        </ul>
    </div><!-- end messages div -->
<?php } ?>

<div class="form_options">
    [ <a href="/variables/bottletype">Create New Bottle Type</a> ]
</div>

<table class="variables_table"  width="840">
    <thead>
        <tr>
            <th colspan=2 class="top-header">Bottle Type Manager</th>
        </tr>
        <tr>
            <th width="400" class="form-header">Bottle Type</th>
            <th width="25" class="form-header"></th>
        </tr>
    </thead>
    <tbody>
        <?php
        $row = 0;
        $accessbottletype = Utility_Functions::canUserAccess("/variables/bottletype");
        foreach ($this->entries as $entry) {
            ?>
            <tr class="row_<?php echo $row % 2; ?>" id="<?php echo $entry['bottle_type_id']; ?>">
                <td><?php echo $entry['bottle_type']; ?></td>
                <td>
    <?php if ($accessbottletype) { ?>
                        <a href="/variables/bottletype/id/<?php echo $entry['bottle_type_id']; ?>">
                            <img title="edit the selected unit's information" src="/images/icons/famfam/pencil.png" />
                        </a>
    <?php } ?>
                </td>
            </tr>
            <?php ++$row; ?>
<?php } ?>
    </tbody>
</table>