<!-- BREAD CRUMB NAVIGATOR PANEL -->
<div class="bread_crumb_module">
    <div class="bread_crumb">	
        <ul>
            <li><a href="/dashboard">Home</a></li>
            <li><?php echo $this->title; ?></li>
        </ul>
    </div><!-- end bread_crumb div -->
</div><!-- end bread_crumb_module div -->
<div class="clear"></div>

<!-- SYSTEM MESSAGES -->
<?php if (is_array($this->messages) && count($this->messages) > 0) { ?>
    <div id="messages">
        <ul>
            <?php foreach ($this->messages as $message) { ?>
                <li><?php echo $message; ?></li>
            <?php } ?>
        </ul>
    </div><!-- end messages div -->
<?php } ?>

<div class="form_options">[ <a href="/variables/captabpackages">Cancel</a> ]</div>

<form enctype="multipart/form-data" method="post" action="">
    <?php echo $this->form->id; ?>
    <table id="form" width="600">
        <tr>
            <td colspan=2 class="top-header">Cap/Tab Package Manager</td>
        </tr>

        <tr>
            <td class="form-header">Cap/Tab Code</td>
            <td class="form-field"><?php echo $this->form->code; ?></td>
        </tr>

        <tr>
            <td class="form-header">Cap/Tab Desc</td>
            <td class="form-field"><?php echo $this->form->name; ?></td>
        </tr>

        <tr>
            <td class="form-header">Cap/Tab Type</td>
            <td class="form-field"><?php echo $this->form->captab_type; ?></td>
        </tr>

        <tr>
            <td class="form-header">Cap/Tab Size</td>
            <td class="form-field">
                <select name="captab_size" class="form-element" id="captab_size">
                    <option value=''>- SELECT SIZE -</option>
                    <?php foreach ($this->sizes as $size) { ?>
                        <option value="<?php echo $size['bulk_size']; ?>" <?php if (html_entity_decode($size['bulk_size']) === html_entity_decode($this->values['captab_size'])) echo 'selected="selected"'; ?>><?php echo $size['bulk_size']; ?></option>
                    <?php } ?>
                </select>
            </td>
        </tr>

        <tr>
            <td class="form-header">Cap/Tab Color</td>
            <td class="form-field"><?php echo $this->form->captab_color; ?></td>
        </tr>

        <tr>
            <td class="form-header" width="220">Has Shell Weight</td>
            <td class="form-field"><?php echo $this->form->captab_weight; ?></td>
        </tr>

        <tr id="shell_weight_info">
            <td class="form-header">Capsule Shell Weight (Unit)</td>
            <td class="form-field"><?php echo $this->form->capsule_shell_weight . $this->form->capsule_shell_weight_unit; ?></td>
        </tr>

        <tr>
            <td class="form-header">Vegan</td>
            <td class="form-field"><?php echo $this->form->vegan; ?></td>
        </tr>

        <tr>
            <td class="form-header">Gelatin Capsule</td>
            <td class="form-field"><?php echo $this->form->gelatin_capsule; ?></td>
        </tr>

        <tr>
            <td class="form-header">Active</td>
            <td class="form-field"><?php echo $this->form->active; ?></td>
        </tr>

        <tr>
            <td colspan=2 class="form-submit"><?php echo $this->form->submit; ?></td>
        </tr>
    </table>
</form>