<!-- BREAD CRUMB NAVIGATOR PANEL -->
<div class="bread_crumb_module">
    <div class="bread_crumb">	
        <ul>
            <li><a href="/dashboard">Home</a></li>
            <li><?php echo $this->title; ?></li>
        </ul>
    </div><!-- end bread_crumb div -->
</div><!-- end bread_crumb_module div -->
<div class="clear"></div>

<!-- SYSTEM MESSAGES -->
<?php if (is_array($this->messages) && count($this->messages) > 0) { ?>
    <div id="messages">
        <ul>
            <?php foreach ($this->messages as $message) { ?>
                <li><?php echo $message; ?></li>
            <?php } ?>
        </ul>
    </div><!-- end messages div -->
<?php } ?>

<?php echo $this->entries; ?>

<div class="form_options">[ <a href="/variables/desiccanttype">Create New Desiccant Type</a> ]</div>

<table class="variables_table">
    <tr>
        <td colspan=2 class="top-header">Desiccant Type Manager</td>
    </tr>
    <tr>
        <td width="400" class="form-header">Desiccant Type</td>
        <td width="25" class="form-header"></td>
    </tr>
    <tbody>
        <?php
        $row = 0;
        $accessDesc = Utility_Functions::canUserAccess("/variables/desiccanttype");
        foreach ($this->entries as $entry) {
            ?>
            <tr class="row_<?php echo $row % 2; ?>" id="<?php echo $entry['desiccant_type_id']; ?>">
                <td><?php echo $entry['desiccant_type']; ?></td>
                <td>
    <?php if ($accessDesc) { ?>
                        <a href="/variables/desiccanttype/id/<?php echo $entry['desiccant_type_id']; ?>">
                            <img title="edit the selected unit's information" src="/images/icons/famfam/pencil.png" />
                        </a>
    <?php } ?>
                </td>
            </tr>
            <?php ++$row; ?>
<?php } ?>
    </tbody>
</table>