<!-- BREAD CRUMB NAVIGATOR PANEL -->
<div class="bread_crumb_module">
    <div class="bread_crumb">	
        <ul>
            <li><a href="/dashboard">Home</a></li>
            <li><?php echo $this->title; ?></li>
        </ul>
    </div><!-- end bread_crumb div -->
</div><!-- end bread_crumb_module div -->
<div class="clear"></div>

<!-- SYSTEM MESSAGES -->
<?php if (is_array($this->messages) && count($this->messages) > 0) { ?>
    <div id="messages">
        <ul>
            <?php foreach ($this->messages as $message) { ?>
                <li><?php echo $message; ?></li>
            <?php } ?>
        </ul>
    </div><!-- end messages div -->
<?php } ?>

<div class="form_options">[ <a href="/variables/lab">Create New Lab</a> ]</div>

<table class="variables_table" width="600">
    <thead>
        <tr>
            <th colspan=3 class="top-header">Lab Manager</th>
        </tr>
        <tr>
            <th width="400" class="form-header">Lab Label</th>
            <th width="75" class="form-header">Status</th>
            <th width="50" class="form-header"></th>
        </tr>
    </thead>
    <tbody>
        <?php
        $row = 0;
        $accesslab = Utility_Functions::canUserAccess("/variables/lab");
        $accesslabactivate = Utility_Functions::canUserAccess("/variables/labactivate");
        $accesslabdeactivate = Utility_Functions::canUserAccess("/variables/labdeactivate");
        foreach ($this->labs as $lab) {
            ?>
            <tr class="row_<?php echo $row % 2; ?>" id="<?php echo $lab['lab_id']; ?>">
                <td><?php echo $lab['lab_name']; ?></td>
                <td><?php echo ( $lab['lab_active'] == 1 ) ? "Active" : "Inactive"; ?></td>
                <td>
    <?php if ($accesslab) { ?>
                        <a href="/variables/lab/id/<?php echo $lab['lab_id']; ?>">
                            <img title="edit the selected lab's information" src="/images/icons/famfam/pencil.png" />
                        </a>
                    <?php } ?>
    <?php if ($lab['lab_active'] == 1 && $accesslabdeactivate) { ?>
                        <a class="variables_deactivate" href="/variables/labdeactivate/id/<?php echo $lab['lab_id']; ?>">
                            <img title="deactivate the selected lab" src="/images/icons/famfam/delete.png" />
                        </a>
    <?php } else if ($lab['lab_active'] == 0 && $accesslabactivate) { ?>
                        <a class="variables_activate" href="/variables/labactivate/id/<?php echo $lab['lab_id']; ?>">
                            <img title="activate the selected lab" src="/images/icons/famfam/add.png" />
                        </a>
    <?php } ?>
                </td>
            </tr>
            <?php ++$row;
        }
        ?>
    </tbody>
</table>