<!-- BREAD CRUMB NAVIGATOR PANEL -->
<div class="bread_crumb_module">
    <div class="bread_crumb">	
        <ul>
            <li><a href="/dashboard">Home</a></li>
            <li><?php echo $this->title; ?></li>
        </ul>
    </div><!-- end bread_crumb div -->
</div><!-- end bread_crumb_module div -->
<div class="clear"></div>

<!-- SYSTEM MESSAGES -->
<?php if (is_array($this->messages) && count($this->messages) > 0) { ?>
    <div id="messages">
        <ul>
            <?php foreach ($this->messages as $message) { ?>
                <li><?php echo $message; ?></li>
            <?php } ?>
        </ul>
    </div><!-- end messages div -->
<?php } ?>

<?php echo $this->entries; ?>

<div class="form_options">

    <div class="search_section">
        <form method="post">
            <?php echo $this->search->field; ?>
            <?php echo $this->search->search; ?>
        </form>
    </div><!-- end search_section div -->
    [ <a href="/variables/sleeving">Create New Sleeving</a> ]</div>

<table class="variables_table" width="500">
    <tr>
        <td colspan="9" class="top-header">Sleevings Manager</td>
    </tr>
    <tr>
        <td width="130" class="form-header">Sleeving Type</td>
        <td width="25" class="form-header">edit</td>
    </tr>
    <tbody>
        <?php
        $row = 0;
        $accessSleev = Utility_Functions::canUserAccess("/variables/sleeving");
        foreach ($this->entries as $entry) {
            ?>
            <tr class="row_<?php echo $row % 2; ?>" id="<?php echo $entry['sleeving_id']; ?>">
                <td><?php echo $entry['sleeving_types']; ?></td>
                <td>
    <?php if ($accessSleev) { ?>
                        <a href="/variables/sleeving/id/<?php echo $entry['sleeving_id']; ?>">
                            <img title="edit the selected unit's information" src="/images/icons/famfam/pencil.png" />
                        </a>
    <?php } ?>
                </td>
            </tr>
            <?php ++$row; ?>
<?php } ?>
    </tbody>
</table>