<!-- BREAD CRUMB NAVIGATOR PANEL -->
<div class="bread_crumb_module">
    <div class="bread_crumb">	
        <ul>
            <li><a href="/dashboard">Home</a></li>
            <li><?php echo $this->title; ?></li>
        </ul>
    </div><!-- end bread_crumb div -->
</div><!-- end bread_crumb_module div -->
<div class="clear"></div>

<!-- SYSTEM MESSAGES -->
<?php if (is_array($this->messages) && count($this->messages) > 0) { ?>
    <div id="messages">
        <ul>
            <?php foreach ($this->messages as $message) { ?>
                <li><?php echo $message; ?></li>
            <?php } ?>
        </ul>
    </div><!-- end messages div -->
<?php } ?>

<?php echo $this->statuses; ?>

<div class="form_options">[ <a href="/variables/status">Create New Status Reason</a> ]</div>

<table class="variables_table">
    <tr>
        <td colspan=3 class="top-header">Status Reasons</td>
    </tr>
    <tr>
        <td width="400" class="form-header">Label</td>
        <td width="75" class="form-header">Status</td>
        <td width="50" class="form-header"></td>
    </tr>
    <tbody>
        <?php
        $counter = 0;
        $accessStatus = Utility_Functions::canUserAccess("/variables/status");
        $accessStatusActivation = Utility_Functions::canUserAccess("/variables/status-activation");
        foreach ($this->statuses as $entry) {
            ?>
            <tr class="row_<?php echo $counter % 2; ?>" id="<?php echo $entry['reason_id']; ?>">
                <td><?php echo $entry['reason']; ?></td>
                <td><?php echo ( $entry['status'] == 1 ) ? "Active" : "Inactive"; ?></td>
                <td>
                    <?php if ($accessStatus) { ?>
                        <a href="/variables/status/id/<?php echo $entry['reason_id'] . "/page/" . $this->page; ?>">
                            <img title="edit the selected status's information" src="/images/icons/famfam/pencil.png" />
                        </a>
                    <?php } ?>
                    <?php if ($entry['status'] == 1 && $accessStatusActivation) { ?>
                        <a class="activation" href="/variables/status-activation/page/<?php echo $this->page; ?>/id/<?php echo $entry['reason_id']; ?>/s/0">
                            <img title="deactivate the selected status" src="/images/icons/famfam/delete.png" />
                        </a>
                    <?php } else if ($entry['status'] == 0 && $accessStatusActivation) { ?>
                        <a class="activation" href="/variables/status-activation/page/<?php echo $this->page; ?>/id/<?php echo $entry['reason_id']; ?>/s/1">
                            <img title="activate the selected status" src="/images/icons/famfam/add.png" />
                        </a>
                    <?php } ?>
                </td>
            </tr>
            <?php ++$counter;
        }
        ?>
    </tbody>
</table>